{% set version = "1.2" %}
{% set sha256 = "552f157861c22a0af22ce19400e6771a8034bdbfedbc760f287a30ac794d36c8" %}

package:
  name: hmftools-bamtools
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/bamtools-v{{ version }}/bamtools-{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("hmftools-bamtools", max_pin="x.x") }}

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - 'bamtools -version | grep BamTools'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/bam-tools/README.md
  license: GPL-3.0-only
  license_family: GPL3
  summary: Rapidly process BAMs for various tasks.
