{% set version = "4.0" %}
{% set sha256 = "" %}

package:
  name: hmftools-purple
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/purple-v{{ version }}/purple_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8
    - xorg-libxtst
    - circos >=0.69.6
    - bioconductor-variantannotation
    - r-cairo
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-tidyr

test:
  commands:
    - 'purple -version | grep Purple'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/purple
  license: GPL-3.0-only
  license_family: GPL3
  summary: PURPLE is a purity ploidy estimator for tumor samples.
