{% set version = "3.0.2" %}
{% set sha256 = "11723a5478bc45ae6c6e5442f7086b78162b3973802c2572441a439751c45713" %}

package:
  name: hmftools-orange
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/orange-v{{ version }}/orange.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-orange', max_pin="x") }}

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - 'orange -version | grep Orange'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/orange/README.md
  license: GPL-3.0-only
  license_family: GPL3
  summary: ORANGE creates a PDF report summarising key outputs from the hmftools workflow.
